# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 17:59
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Samardzici'), (19760525, 'Ceca'), (19760702, 'Nenad'), (20110913, 'Nole'), (20150102, 'Luna')], max_length=37, null=True),
        ),
    ]
